### ISSUE TITLE
Sharper knives for filter_time_period in combination with trim

### ISSUE THREAD

**Issue by wfeijen** [gertjanssenswillen/edeaR#11]
What I expected: When trimming to a specific time period is that events that are partly in the time period are also trimmed so that they stay in the result.

What I got: Events that are only partly in the trimmed period are discarded.

Why is this a problem?: We use trim mainly to slice a larger period in even parts so that we can measure what the total processing time is per part. This is only possible when events also sliced and attribute processing time to the right part. Which is why we need the sharper knife which also cuts the raisins in the cake.

Note: for the other filter options: "contained", "intersecting", "start", "complete" there is no problem.

**Comment by gertjanssenswillen** [comment]
I have added an option "force_trim" to the filter. If set to TRUE, it will cut the activity instances on the edges at the exact point of the time period. Hope this is what you need.

**Comment by wfeijenOI** [comment]
Hi, It is exactly what I need. 

I am sorry, for taking so long to test.
