### ISSUE TITLE
activity_frequency(level = "activity") vs n_events()

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/edeaR#13]
Hello Gert,

I'm using the activity_frequency (level = "activity") and n_events ().

What I see is that n_events () has twice the number of events compared to activity_frequency (level = "activity") (perhaps due to the start/full state).

Thank you.

**Comment by gertjanssenswillen** [comment]
Hi

This is expected if each activity instance has a start and complete timestamp. Note that an "event" is different from an "activity_instance": an event is atomic (has only one timestamp); an activity instance can be related to multiple events and can have a duration. 

The information in activity_frequency should correspond with the output of n_activity_instances. 

It can be that each activity instance has only one event, in which both quantities you mention will be equal, but this is not necessarily the case.

**Comment by Nipi** [comment]
Thanks Gert.
