### ISSUE TITLE
start_activities() shows unexpected column label

### ISSUE THREAD

**Issue by larspijnappel** [gertjanssenswillen/edeaR#17]
Have a look at `patients %>% start_activities(level = "case")`. The output is as expected, it's just that the column label is a bit confusing (showing `end_activity`).

**Comment by gertjanssenswillen** [comment]
Not sure whether the column name should be "start_activity", or just the activity id name for both start and end activities. I suppose the latter would be more consistent with other functions. Thoughts?

**Comment by gertjanssenswillen** [comment]
All headers referring to activities now show the column name of the activity id. This was already for all other levels of these metrics.
