### ISSUE TITLE
Add method "only" for filter_activivty_presence() 

### ISSUE THREAD

**Issue by serkserk** [gertjanssenswillen/edeaR#21]
Hi, I would like to suggest a new parameter option for the `filter_activivty_presence()` function
Currently you can ony show data that pass on all activity from a list or only 1 activity of a list (`all` or `one_off`)
Adding a third option which filter data that only pass on the listed activites would be very helpfull.
Using   
`filter_activivty_presence(c("A","B","C","D")) `
will filter a process passing in "A","B","A","C","D"  and not show a process passing in "A","B","C","D","E"

**Comment by gertjanssenswillen** [comment]
Thanks for this suggestion! I though it over and actually added two new methods, "only" and "exact". _only_ keeps cases that consist out of the specified activities (say A B C D), but should not have all of these.  _exact_ keeps cases that consist out of exactly the specified activities (i.e. only those and all those; but they can occur more than once and in any order).

![image](https://user-images.githubusercontent.com/8807203/49527022-542dfd00-f8b1-11e8-88a8-597f5728b7e9.png)


Hope this is what you are looking for? Then this issue can be closed

**Comment by serkserk** [comment]
Yes, it's exactly what I need when I work with process variant.
Currently I was aggregating the activity list for every case to get data on my variant before creating my logs which was not optimal
