### ISSUE TITLE
`filter_throughput_time` fails when using `week` units

### ISSUE THREAD

**Issue by jgonzale** [gertjanssenswillen/edeaR#23]
Hi.

I'm trying to filter my event log to discard those cases longer than 10 weeks, and I found this situation.

```R
> eventlog_ %>% filter_throughput_time(interval = c(10, NA), units = "week")
Error in mutate_impl(.data, dots) : 
  Evaluation error: invalid units specified.
```

Otherwise, if I use a different time unit, it works seamlessly.

```R
> eventlog %>% filter_throughput_time(interval = c(10, NA), units = "days")
Event log consisting of:
4480 events
52 traces
684 cases
12 activities
4480 activity instances

# A tibble: 4,480 x 14
[...]
```

Is there anything I'm doing wrong?

**Comment by gertjanssenswillen** [comment]
Seems there was a bug here which I just fixed. It should be working now if you install the package from github.
