### ISSUE TITLE
Endpoint filter does not work

### ISSUE THREAD

**Issue by fmannhardt** [gertjanssenswillen/edeaR#25]
https://github.com/gertjanssenswillen/edeaR/blob/695c0fdc2a4ce39acca491cd01e9cd128411e518/R/filter_endpoints_percentile.R#L22

This does not provide a list of cases anymore. Maybe changes in dplyr or somewhere else in edeaR?

**Comment by gertjanssenswillen** [comment]
Seems the case id's got lost somewhere, there was a messed up code chunk above. Also made the pull more robust so that the error message would at least be intellegible.

**Comment by fmannhardt** [comment]
thanks
