### ISSUE TITLE
eventlog function

### ISSUE THREAD

**Issue by koalabearski** [gertjanssenswillen/edeaR#6]
It seems like the eventlog function is missing from the edeaR package, is it?  I don't see it in the package or in the documention, there is only an eventlog_from_xes function.  The eventlog function is referenced in the vignette on data preprocessing in the importing from csv section.

**Comment by gertjanssenswillen** [comment]
The event log function and other basic functions have been moved to the package bupaR. This is currently on cran. I will also upload the latest version to github soon.

My apologies for the misunderstanding. We are currently revising the packages and building a website with updated documentation. Thanks for your patience.

**Comment by koalabearski** [comment]
Fantastic!  Looking forward to the updates, I've just started van der Alast's "Process Mining" text and am exploring all the available tools right now and am glad to see this work continuing.
