### ISSUE TITLE
start_activity and activity_frequency

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/edeaR#9]
Hi, thanks for the bupaR package, it is very useful!
I am having an issue using start_activity() and activity_frequency() functions:

1) evl %>% start_activities(level = "case")
2) evl %>% activity_frequency("case")

where evl is an eventlog object. The output is:
1) a data frame with only one row;
2) never stop running.

Any suggestion?

Thanks.

**Comment by gertjanssenswillen** [comment]
Thanks for mentioning. The issue with start_activity is solved by the latest commit. Please install edeaR again from github.

About activity_frequency: what are the dimensions of evl? I.e. number of rows, number of cases?

**Comment by Nipi** [comment]
Thanks for your answer.

I am working with an eventlog of 3.5 milions rows with 150k cases. I know that it is big, but it worked well in the previous release.

Is there some correlation with level = "case"?

Any suggestion?

**Comment by gertjanssenswillen** [comment]
I have push an update of the activity frequency function. I do not immediately have a large dataset to see if it improved. Could you test whether this works better?

**Comment by Nipi** [comment]
The function activity_frequency is working well in the latest release from GitHub.

Thanks a lot!

**Comment by gertjanssenswillen** [comment]
You're welcome!

**Comment by Nipi** [comment]
Now it works well on nodes: all the nodes are named in the correct way.

But I noticed something strange on arcs: there are some "NA Days" as duration.

Thanks too much.

![cattura](https://user-images.githubusercontent.com/18727013/33893567-0280f1fc-df5c-11e7-874d-a04b91d26671.PNG)
